//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonelTB()
        {
            this.TransactionTB = new HashSet<TransactionTB>();
        }
    
        public int P_Id { get; set; }
        public string P_Ad { get; set; }
        public string P_Soyad { get; set; }
        public string P_Yetki { get; set; }
        public string P_Mail { get; set; }
        public string P_Sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionTB> TransactionTB { get; set; }
    }
}
