//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokTB
    {
        public int S_Id { get; set; }
        public int U_Id { get; set; }
        public byte Wh_Id { get; set; }
        public int U_Adet { get; set; }
        public string U_Raf { get; set; }
    
        public virtual ItemTB ItemTB { get; set; }
        public virtual WarehouseTB WarehouseTB { get; set; }
    }
}
