//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTB
    {
        public int T_Id { get; set; }
        public int U_Id { get; set; }
        public byte T_Type { get; set; }
        public byte S_Depo { get; set; }
        public byte T_Depo { get; set; }
        public int T_Adet { get; set; }
        public System.DateTime T_Date { get; set; }
        public int T_Personel { get; set; }
    
        public virtual ItemTB ItemTB { get; set; }
        public virtual PersonelTB PersonelTB { get; set; }
        public virtual TransactionTypePerTB TransactionTypePerTB { get; set; }
        public virtual TransactionTypeAdTB TransactionTypeAdTB { get; set; }
        public virtual WarehouseTB WarehouseTB { get; set; }
        public virtual WarehouseTB WarehouseTB1 { get; set; }
    }
}
